/*
 * Mist API
 *
 * > Version: **2409.1.9** > > Date: **September 27, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates] (https://www.juniper.net/documentation/us/en/software/mist/api/http/getting-started/how-to-get-started)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 
 *
 * API version: 2409.1.9
 * Contact: tmunzer@juniper.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mist

type AssetOfInterest struct {
	ApMac string `json:"ap_mac,omitempty"`
	Beam float64 `json:"beam,omitempty"`
	By string `json:"by,omitempty"`
	CurrSite string `json:"curr_site,omitempty"`
	DeviceName string `json:"device_name,omitempty"`
	Id string `json:"id,omitempty"`
	LastSeen float64 `json:"last_seen,omitempty"`
	Mac string `json:"mac,omitempty"`
	Manufacture string `json:"manufacture,omitempty"`
	MapId string `json:"map_id,omitempty"`
	Name string `json:"name,omitempty"`
	Rssi float64 `json:"rssi,omitempty"`
}
