/*
 * Mist API
 *
 * > Version: **2409.1.9** > > Date: **September 27, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates] (https://www.juniper.net/documentation/us/en/software/mist/api/http/getting-started/how-to-get-started)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 
 *
 * API version: 2409.1.9
 * Contact: tmunzer@juniper.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Wi-Fi site settings
type SiteWifi struct {
	CiscoEnabled bool `json:"cisco_enabled,omitempty"`
	// whether to disable 11k
	Disable11k bool `json:"disable_11k,omitempty"`
	DisableRadiosWhenPowerConstrained bool `json:"disable_radios_when_power_constrained,omitempty"`
	// when proxy_arp is enabled, check for arp spoofing.
	EnableArpSpoofCheck bool `json:"enable_arp_spoof_check,omitempty"`
	EnableSharedRadioScanning bool `json:"enable_shared_radio_scanning,omitempty"`
	// enable WIFI feature (using SUB-MAN license)
	Enabled bool `json:"enabled,omitempty"`
	// whether to locate connected clients
	LocateConnected bool `json:"locate_connected,omitempty"`
	// whether to locate unconnected clients
	LocateUnconnected bool `json:"locate_unconnected,omitempty"`
	// whether to allow Mesh to use DFS channels. For DFS channels, Remote Mesh AP would have to do CAC when scanning for new Base AP, which is slow and will distrupt the connection. If roaming is desired, keep it disabled.
	MeshAllowDfs bool `json:"mesh_allow_dfs,omitempty"`
	// used to enable/disable CRM
	MeshEnableCrm bool `json:"mesh_enable_crm,omitempty"`
	// whether to enable Mesh feature for the site
	MeshEnabled bool `json:"mesh_enabled,omitempty"`
	// optional passphrase of mesh networking, default is generated randomly
	MeshPsk string `json:"mesh_psk,omitempty"`
	// optional ssid of mesh networking, default is based on site_id
	MeshSsid string `json:"mesh_ssid,omitempty"`
	ProxyArp *AllOfsiteWifiProxyArp `json:"proxy_arp,omitempty"`
}
