/*
 * Mist API
 *
 * > Version: **2409.1.9** > > Date: **September 27, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates] (https://www.juniper.net/documentation/us/en/software/mist/api/http/getting-started/how-to-get-started)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 
 *
 * API version: 2409.1.9
 * Contact: tmunzer@juniper.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// LicenseType : enum: `SUB-AST`, `SUB-DATA`, `SUB-ENG`, `SUB-EX12`, `SUB-EX24`, `SUB-EX48`, `SUB-MAN`, `SUB-ME`, `SUB-PMA`, `SUB-SRX1`, `SUB-SRX2`, `SUB-SVNA`, `SUB-VNA`, `SUB-WAN1`, `SUB-WAN2`, `SUB-WVNA1`, `SUB-WVNA2`
type LicenseType string

// List of license_type
const (
	AST_LicenseType LicenseType = "SUB-AST"
	DATA_LicenseType LicenseType = "SUB-DATA"
	ENG_LicenseType LicenseType = "SUB-ENG"
	EX12_LicenseType LicenseType = "SUB-EX12"
	EX24_LicenseType LicenseType = "SUB-EX24"
	EX48_LicenseType LicenseType = "SUB-EX48"
	MAN_LicenseType LicenseType = "SUB-MAN"
	ME_LicenseType LicenseType = "SUB-ME"
	PMA_LicenseType LicenseType = "SUB-PMA"
	SRX1_LicenseType LicenseType = "SUB-SRX1"
	SRX2_LicenseType LicenseType = "SUB-SRX2"
	SVNA_LicenseType LicenseType = "SUB-SVNA"
	VNA_LicenseType LicenseType = "SUB-VNA"
	WAN1_LicenseType LicenseType = "SUB-WAN1"
	WAN2_LicenseType LicenseType = "SUB-WAN2"
	WVNA1_LicenseType LicenseType = "SUB-WVNA1"
	WVNA2_LicenseType LicenseType = "SUB-WVNA2"
)
