/*
 * Mist API
 *
 * > Version: **2409.1.9** > > Date: **September 27, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates] (https://www.juniper.net/documentation/us/en/software/mist/api/http/getting-started/how-to-get-started)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 
 *
 * API version: 2409.1.9
 * Contact: tmunzer@juniper.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mist

// IoT AP settings
type ApIot struct {
	A1 *AllOfapIotA1 `json:"A1,omitempty"`
	A2 *AllOfapIotA2 `json:"A2,omitempty"`
	A3 *AllOfapIotA3 `json:"A3,omitempty"`
	A4 *AllOfapIotA4 `json:"A4,omitempty"`
	DI1 *AllOfapIotDi1 `json:"DI1,omitempty"`
	DI2 *AllOfapIotDi2 `json:"DI2,omitempty"`
	DO *AllOfapIotDo `json:"DO,omitempty"`
}
