/*
 * Mist API
 *
 * > Version: **2409.1.9** > > Date: **September 27, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates] (https://www.juniper.net/documentation/us/en/software/mist/api/http/getting-started/how-to-get-started)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 
 *
 * API version: 2409.1.9
 * Contact: tmunzer@juniper.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// MxTunnels statistics
type StatsMxtunnel struct {
	Ap string `json:"ap,omitempty"`
	ForSite bool `json:"for_site,omitempty"`
	LastSeen float64 `json:"last_seen,omitempty"`
	MxclusterId string `json:"mxcluster_id,omitempty"`
	MxedgeId string `json:"mxedge_id,omitempty"`
	MxtunnelId string `json:"mxtunnel_id,omitempty"`
	OrgId string `json:"org_id,omitempty"`
	// MxEdge ID of the peer(mist edge to mist edge tunnel)
	PeerMxedgeId string `json:"peer_mxedge_id,omitempty"`
	RemoteIp string `json:"remote_ip,omitempty"`
	RemotePort int32 `json:"remote_port,omitempty"`
	RxControlPkts int32 `json:"rx_control_pkts,omitempty"`
	// list of sessions
	Sessions []StatsMxtunnelSession `json:"sessions,omitempty"`
	SiteId string `json:"site_id,omitempty"`
	State *AllOfstatsMxtunnelState `json:"state,omitempty"`
	TxControlPkts int32 `json:"tx_control_pkts,omitempty"`
	Uptime int32 `json:"uptime,omitempty"`
}
