/*
 * Mist API
 *
 * > Version: **2409.1.9** > > Date: **September 27, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates] (https://www.juniper.net/documentation/us/en/software/mist/api/http/getting-started/how-to-get-started)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 
 *
 * API version: 2409.1.9
 * Contact: tmunzer@juniper.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// SsoOauthType : if `idp_type`==`oauth`. enum: `azure`, `azure-gov`, `okta`, `ping_identity`
type SsoOauthType string

// List of sso_oauth_type
const (
	AZURE_SsoOauthType SsoOauthType = "azure"
	AZURE_GOV_SsoOauthType SsoOauthType = "azure-gov"
	OKTA_SsoOauthType SsoOauthType = "okta"
	PING_IDENTITY_SsoOauthType SsoOauthType = "ping_identity"
)
