/*
 * Mist API
 *
 * > Version: **2409.1.9** > > Date: **September 27, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates] (https://www.juniper.net/documentation/us/en/software/mist/api/http/getting-started/how-to-get-started)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 
 *
 * API version: 2409.1.9
 * Contact: tmunzer@juniper.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// whether this network has direct internet access
type NetworkInternetAccess struct {
	CreateSimpleServicePolicy bool `json:"create_simple_service_policy,omitempty"`
	// Property key may be an IP/Port (i.e. \"63.16.0.3:443\"), or a port (i.e. \":2222\")
	DestinationNat map[string]NetworkDestinationNatProperty `json:"destination_nat,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	// by default, all access is allowed, to only allow certain traffic, make `restricted`=`true` and define service_policies
	Restricted bool `json:"restricted,omitempty"`
	// Property key may be an IP Address (i.e. \"172.16.0.1\"), and IP Address and Port (i.e. \"172.16.0.1:8443\") or a CIDR (i.e. \"172.16.0.12/20\")
	StaticNat map[string]NetworkStaticNatProperty `json:"static_nat,omitempty"`
}
