/*
 * Mist API
 *
 * > Version: **2409.1.9** > > Date: **September 27, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates] (https://www.juniper.net/documentation/us/en/software/mist/api/http/getting-started/how-to-get-started)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 
 *
 * API version: 2409.1.9
 * Contact: tmunzer@juniper.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mist

type ResponsePcapSearchItem struct {
	ApMacs []string `json:"ap_macs,omitempty"`
	Aps []string `json:"aps,omitempty"`
	Duration float64 `json:"duration,omitempty"`
	Format string `json:"format,omitempty"`
	Id string `json:"id,omitempty"`
	MaxNumPackets float64 `json:"max_num_packets,omitempty"`
	OrgId string `json:"org_id,omitempty"`
	PcapAps map[string]ResponsePcapSearchItemPcapApsItem `json:"pcap_aps,omitempty"`
	PcapUrl string `json:"pcap_url,omitempty"`
	SiteId string `json:"site_id,omitempty"`
	TerminationReason string `json:"termination_reason,omitempty"`
	Timestamp float64 `json:"timestamp"`
	Type_ string `json:"type"`
	Url string `json:"url"`
}
