/*
 * Mist API
 *
 * > Version: **2409.1.9** > > Date: **September 27, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates] (https://www.juniper.net/documentation/us/en/software/mist/api/http/getting-started/how-to-get-started)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 
 *
 * API version: 2409.1.9
 * Contact: tmunzer@juniper.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SwitchPortUsageDynamicRule struct {
	Equals string `json:"equals,omitempty"`
	// use `equals_any` to match any item in a list
	EqualsAny []string `json:"equals_any,omitempty"`
	// \"[0:3]\":\"abcdef\" -> \"abc\" \"split(.)[1]\": \"a.b.c\" -> \"b\" \"split(-)[1][0:3]: \"a1234-b5678-c90\" -> \"b56\"
	Expression string `json:"expression,omitempty"`
	Src *AllOfswitchPortUsageDynamicRuleSrc `json:"src"`
	// `port_usage` name
	Usage string `json:"usage,omitempty"`
}
