/*
 * Mist API
 *
 * > Version: **2409.1.9** > > Date: **September 27, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates] (https://www.juniper.net/documentation/us/en/software/mist/api/http/getting-started/how-to-get-started)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 
 *
 * API version: 2409.1.9
 * Contact: tmunzer@juniper.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AllOfroutingPolicyTermMatching struct {
	// takes regular expression
	AsPath []string `json:"as_path,omitempty"`
	Community []string `json:"community,omitempty"`
	Network []string `json:"network,omitempty"`
	// zero or more criteria/filter can be specified to match the term, all criteria have to be met
	Prefix []string `json:"prefix,omitempty"`
	// `direct`, `bgp`, `osp`, ...
	Protocol []string `json:"protocol,omitempty"`
	RouteExists *RoutingPolicyTermMatchingRouteExists `json:"route_exists,omitempty"`
	// overlay-facing criteria (used for bgp_config where via=vpn)
	VpnNeighborMac []string `json:"vpn_neighbor_mac,omitempty"`
	// overlay-facing criteria (used for bgp_config where via=vpn) ordered-
	VpnPath []string `json:"vpn_path,omitempty"`
	VpnPathSla *RoutingPolicyTermMatchingVpnPathSla `json:"vpn_path_sla,omitempty"`
}
