/*
 * Mist API
 *
 * > Version: **2409.1.9** > > Date: **September 27, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates] (https://www.juniper.net/documentation/us/en/software/mist/api/http/getting-started/how-to-get-started)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 
 *
 * API version: 2409.1.9
 * Contact: tmunzer@juniper.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NacCrlFile struct {
	// Time at which the file was first uploaded, in epoch
	CreatedTime float64 `json:"created_time,omitempty"`
	// ID for file upload, used to identify file even for deletion
	Id string `json:"id,omitempty"`
	// Time at which the file was last updated, in epoch
	ModifiedTime float64 `json:"modified_time,omitempty"`
	// Name for the .crl file issuer if set
	Name string `json:"name,omitempty"`
	// Download URL for the .crl file
	Url string `json:"url,omitempty"`
}
