/*
 * Mist API
 *
 * > Version: **2409.1.9** > > Date: **September 27, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates] (https://www.juniper.net/documentation/us/en/software/mist/api/http/getting-started/how-to-get-started)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 
 *
 * API version: 2409.1.9
 * Contact: tmunzer@juniper.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mist

type MspLicenseAction struct {
	// required if `op`==`unamend`
	AmendmentId string `json:"amendment_id,omitempty"`
	// required if `op`==`amend`, destination org id
	DstOrgId string `json:"dst_org_id,omitempty"`
	// required if `op`== `annotate`
	Notes string `json:"notes,omitempty"`
	Op *AllOfmspLicenseActionOp `json:"op"`
	// required if `op`==`amend`
	Quantity float64 `json:"quantity,omitempty"`
	// required if `op`== `annotate`
	SubscriptionId string `json:"subscription_id,omitempty"`
}
