/*
 * Mist API
 *
 * > Version: **2409.1.9** > > Date: **September 27, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates] (https://www.juniper.net/documentation/us/en/software/mist/api/http/getting-started/how-to-get-started)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 
 *
 * API version: 2409.1.9
 * Contact: tmunzer@juniper.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// WebhookTopic : enum: `alarms`, `asset-raw`, `asset-raw-rssi`, `audits`, `client-info`, `client-join`, `client-latency`, `client-sessions`, `device-updowns`, `device-events`, `discovered-raw-rssi`, `location`, `location_asset`, `location_centrak`, `location_client`, `location_sdk`, `location_unclient`, `mxedge-events`, `nac-accounting`, `nac_events`, `occupancy-alerts`, `rssizone`, `sdkclient_scan_data`, `site_sle`, `vbeacon`, `wifi-conn-raw`, `wifi-unconn-raw`, `zone`
type WebhookTopic string

// List of webhook_topic
const (
	ALARMS_WebhookTopic WebhookTopic = "alarms"
	ASSET_RAW_WebhookTopic WebhookTopic = "asset-raw"
	ASSET_RAW_RSSI_WebhookTopic WebhookTopic = "asset-raw-rssi"
	AUDITS_WebhookTopic WebhookTopic = "audits"
	CLIENT_INFO_WebhookTopic WebhookTopic = "client-info"
	CLIENT_JOIN_WebhookTopic WebhookTopic = "client-join"
	CLIENT_LATENCY_WebhookTopic WebhookTopic = "client-latency"
	CLIENT_SESSIONS_WebhookTopic WebhookTopic = "client-sessions"
	DEVICE_EVENTS_WebhookTopic WebhookTopic = "device-events"
	DEVICE_UPDOWNS_WebhookTopic WebhookTopic = "device-updowns"
	DISCOVERED_RAW_RSSI_WebhookTopic WebhookTopic = "discovered-raw-rssi"
	LOCATION_WebhookTopic WebhookTopic = "location"
	LOCATION_ASSET_WebhookTopic WebhookTopic = "location_asset"
	LOCATION_CENTRAK_WebhookTopic WebhookTopic = "location_centrak"
	LOCATION_CLIENT_WebhookTopic WebhookTopic = "location_client"
	LOCATION_SDK_WebhookTopic WebhookTopic = "location_sdk"
	LOCATION_UNCLIENT_WebhookTopic WebhookTopic = "location_unclient"
	MXEDGE_EVENTS_WebhookTopic WebhookTopic = "mxedge-events"
	NAC_ACCOUNTING_WebhookTopic WebhookTopic = "nac-accounting"
	NAC_EVENTS_WebhookTopic WebhookTopic = "nac_events"
	OCCUPANCY_ALERTS_WebhookTopic WebhookTopic = "occupancy-alerts"
	RSSIZONE_WebhookTopic WebhookTopic = "rssizone"
	SDKCLIENT_SCAN_DATA_WebhookTopic WebhookTopic = "sdkclient_scan_data"
	SITE_SLE_WebhookTopic WebhookTopic = "site_sle"
	VBEACON_WebhookTopic WebhookTopic = "vbeacon"
	WIFI_CONN_RAW_WebhookTopic WebhookTopic = "wifi-conn-raw"
	WIFI_UNCONN_RAW_WebhookTopic WebhookTopic = "wifi-unconn-raw"
	ZONE_WebhookTopic WebhookTopic = "zone"
)
